import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import PublicNav from "@/components/layout/PublicNav";
import Logo from "@/components/brand/Logo";

export default function TermsPage() {
  return (
    <div className="vd min-h-screen bg-surface">
      <PublicNav />

      <main className="vd-landing-wrap py-24 md:py-32">
        <Link 
          href="/" 
          className="inline-flex items-center gap-2 text-sm text-ink-muted hover:text-ink transition-colors mb-8"
        >
          <ArrowLeft size={16} />
          Back to home
        </Link>

        <header className="mb-12">
          <p className="vd-eyebrow mb-2">Legal</p>
          <h1 className="vd-serif text-4xl md:text-5xl lg:text-6xl mb-6">
            Terms of <em>Service.</em>
          </h1>
          <p className="text-ink-secondary text-lg max-w-2xl">
            Please read these terms carefully before using the VeraDoc platform. By using our service, you agree to be bound by these terms.
          </p>
        </header>

        <div className="prose prose-slate max-w-3xl">
          <section className="mb-10">
            <h2 className="text-xl font-semibold text-ink mb-4">1. Acceptance of Terms</h2>
            <p className="text-ink-secondary leading-relaxed">
              VeraDoc provides its service to you subject to the following Terms of Service (&quot;TOS&quot;). We reserve the right to update and change the TOS from time to time without notice.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-ink mb-4">2. Description of Service</h2>
            <p className="text-ink-secondary leading-relaxed">
              VeraDoc is an AI-powered document verification platform. Our service includes document analysis, forensic reporting, and trust score generation for academic certificates and transcripts.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-ink mb-4">3. No Legal Advice / Not Binding</h2>
            <p className="text-ink-secondary leading-relaxed p-4 bg-forest-light/20 border-l-4 border-forest italic">
              VeraDoc results are generated by artificial intelligence models. While we strive for extreme accuracy, our verifications are not legally binding and should be used as a screening tool alongside traditional background checks. VeraDoc is not a substitute for official verification from the issuing institution.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-ink mb-4">4. User Responsibilities</h2>
            <p className="text-ink-secondary leading-relaxed mb-4">
              You agree to:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-ink-secondary">
              <li>Provide true, accurate, and current information about yourself and your organisation.</li>
              <li>Maintain the security of your account and password.</li>
              <li>Only upload documents that you have a legal right or permission to verify.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-ink mb-4">5. Payments and Refunds</h2>
            <p className="text-ink-secondary leading-relaxed">
              Verifications are paid for using credits. Credits are non-refundable once purchased. If a verification fails due to a technical error on our part, we will refund the specific credit used for that analysis.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-ink mb-4">6. Limitation of Liability</h2>
            <p className="text-ink-secondary leading-relaxed">
              VeraDoc shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or the inability to use the service or for the cost of procurement of substitute goods and services.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-ink mb-4">7. Termination</h2>
            <p className="text-ink-secondary leading-relaxed">
              We reserve the right to terminate your account if you violate these terms or use the service for fraudulent activities.
            </p>
          </section>
        </div>
      </main>

      <footer className="vd-footer">
        <div className="vd-landing-wrap">
          <div className="vd-footer-grid">
            <div>
              <Logo href="/" />
              <p className="vd-footer-tagline">
                AI-powered document trust for a more transparent educational ecosystem in Nigeria.
              </p>
            </div>
            <div className="vd-footer-col">
              <h4>Product</h4>
              <Link href="/#how-it-works">How it works</Link>
              <Link href="/#pricing">Pricing</Link>
              <Link href="/auth/register">Register</Link>
            </div>
            <div className="vd-footer-col">
              <h4>Resources</h4>
              <Link href="/terms">Terms of Service</Link>
              <Link href="/privacy">Privacy Policy</Link>
              <a href="https://github.com/SQUADHACKATHON3" target="_blank" rel="noopener noreferrer">GitHub</a>
            </div>
          </div>
          <p className="vd-footer-copy">
            © 2026 VeraDoc · Built for Squad Hackathon 3.0 · The Dev Team, OAU Ile-Ife
          </p>
        </div>
      </footer>
    </div>
  );
}
